### ISSUE TITLE
Option to specify Apns -> NotificationOptions.apns_priority

### ISSUE THREAD

**Issue by 0xacdc** [threema-ch/push-relay#32]
https://github.com/threema-ch/push-relay/blob/9cd0c04405d75b4821bb78a7a6b91e19027fb4f8/src/push/apns.rs#L66

Can you please provide an option to specify the priority from config.ini or another config ?

**Comment by dbrgn** [comment]
We could, but what would be the use case of setting the push priority to something other than high?

**Comment by 0xacdc** [comment]
on iOS 13, notifications delivered with High Priority (= 10) are rejected by the system, but if I change `apns_priority: Priority::Normal` - then all works like expected

**Comment by dbrgn** [comment]
Does your application have permission to use silent pushes (AKA voip pushes)? We [use those](https://github.com/threema-ch/push-relay/blob/9cd0c04405d75b4821bb78a7a6b91e19027fb4f8/src/push/apns.rs#L72).

**Comment by 0xacdc** [comment]
Yes our app has permission to use silent pushes, but as I know, they are not equivalent to void pushes (we are not using Pushkit)

**Comment by dbrgn** [comment]
Whether or not it's a VoIP push depends on whether or not you append `.voip` to your bundle ID.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

It seems that a silent push without a voip bundle ID will not wake up your application if it's not started. Could that be the case?

For a priority other than 10 (high), Apple writes:

> Specify 5 to send the notification based on power considerations on the user’s device. Use this priority for notifications that have a payload that includes the content-available key. Notifications with this priority might be grouped and delivered in bursts to the user’s device. They may also be throttled, and in some cases not delivered.

What exactly is your use case?

**Comment by dbrgn** [comment]
Note also that Apple is trying to stop the use of silent pushes for all use cases except for VoIP applications. See also: https://stackoverflow.com/questions/57871677/ios-13-silent-push-notifications-are-no-longer-reliable

Would unreliable and potentially delayed / bundled pushes be OK for your use case?

**Comment by 0xacdc** [comment]
Our use case is to wake our application from the suspended state only. We don't need voip pushes and as you have mentioned it will be soon impossible and forbidden. 

So according to our case, and information from `Table 8-2APNs request headers` from [here:](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1)

>  
    The priority of the notification. Specify one of the following values:
    10 – Send the push message immediately. Notifications with this priority must trigger 
    an alert, sound, or badge on the target device. It is an error to use this priority for 
    a push notification that contains only the content-available key.

    5—Send the push message at a time that takes into account power considerations 
    for the device. Notifications with this priority might be grouped and delivered in 
    bursts.
    They are throttled, and in some cases are not delivered.

So that's why I'm asking about changing apns-priority

**Comment by lgrahl** [comment]
The way I see it that this push relay is highly customised for the use with the Threema Web client code. It would require entangling that first and making the project more generic.

**Comment by 0xacdc** [comment]
ok, Thanks for your time
