### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 0xacdc** [threema-ch/push-relay#33]
Hi, I'm unfamiliar with Rust, and after investigated your service, I got the impression that you are creating a new connection with APNS server for every request. 

Is that true ? You are not reusing/caching already created connections ?

Thanks

**Comment by dbrgn** [comment]
Hi. No, the [`a2`](https://github.com/pimeys/a2) library does connection pooling when reusing the `Client` instance (see https://github.com/threema-ch/push-relay/blob/master/src/server.rs#L43-L55).

From the `a2` README:

> When using the same Client for multiple requests, the Client keeps the connection alive if pushing steady traffic through it.

I have not verified this using network inspection tools, but the fact that we're not getting blocked by Apple's IPs is a strong indicator that we're not opening thousands of connections per hour :slightly_smiling_face:

**Comment by 0xacdc** [comment]
Perfect 👍 ! thanks for quick answer
